using System.Globalization;
using System.Text;
using System.Text.Json;
using ShardLauncher.Patching;

namespace ShardLauncher.Core;

public sealed class VersionStore(InstallLayout layout, LauncherLog log)
{
    public const string IndexName = ".files.json";
    public const string GumpsSub = "gumps";

    public SortedDictionary<string, string>? ReadIndex(long serial)
    {
        var p = Path.Combine(layout.VersionDir(serial), IndexName);
        if (serial <= 0 || !File.Exists(p)) return null;
        try { return JsonSerializer.Deserialize<SortedDictionary<string, string>>(File.ReadAllBytes(p)); }
        catch (JsonException) { return null; }
    }

    public bool IndexEquals(long serial, IDictionary<string, string> expected)
    {
        var idx = ReadIndex(serial);
        return idx is not null && idx.Count == expected.Count && expected.All(kv => idx.TryGetValue(kv.Key, out var v) && v == kv.Value);
    }

    public CuoCheck Verify(long serial)
    {
        var idx = ReadIndex(serial);
        if (idx is null) return new(false, $"version {serial} has no index");
        foreach (var (rel, sha) in idx)
        {
            var p = PathOf(serial, rel);
            if (!File.Exists(p)) return new(false, $"version {serial}: {rel} missing");
            if (Hashing.HashFile(p).Sha256 != sha) return new(false, $"version {serial}: {rel} corrupted");
        }
        return new(true, "ok");
    }

    public string PathOf(long serial, string rel) => CuoInstaller.SafeJoin(layout.VersionDir(serial), rel);

    public IEnumerable<long> Serials() =>
        Directory.Exists(layout.ArtVersions)
            ? Directory.GetDirectories(layout.ArtVersions).Select(Path.GetFileName)
                .Where(n => long.TryParse(n, NumberStyles.None, CultureInfo.InvariantCulture, out _))
                .Select(n => long.Parse(n!, CultureInfo.InvariantCulture))
            : Enumerable.Empty<long>();

    public string? FindLocal(string sha, long size, IEnumerable<string>? extra = null)
    {
        var candidates = Serials().SelectMany(s => (ReadIndex(s) ?? new()).Where(kv => kv.Value == sha).Select(kv => PathOf(s, kv.Key)));
        foreach (var p in candidates.Concat(extra ?? Enumerable.Empty<string>()))
            if (File.Exists(p) && new FileInfo(p).Length == size && Hashing.HashFile(p).Sha256 == sha) return p;
        return null;
    }

    public void Prune(params long[] keep)
    {
        foreach (var s in Serials().Where(s => !keep.Contains(s)))
        {
            try { Directory.Delete(layout.VersionDir(s), true); log.Info($"pruned art version {s}"); }
            catch (Exception e) when (e is IOException or UnauthorizedAccessException) { log.Warn($"prune {s}: {e.Message}"); }
        }
    }

    public static string BuildOverride(PatchManifest m, IEnumerable<string> presentArt, string finalDir)
    {
        var have = new HashSet<string>(presentArt, StringComparer.OrdinalIgnoreCase);
        var sb = new StringBuilder("# generated by ShardLauncher; do not edit\n");
        foreach (var (k, v) in m.OverrideMap ?? new())
        {
            var name = DestRules.Parse(v).FileName;
            if (have.Contains(name)) sb.Append(k).Append('=').Append(Path.Combine(finalDir, name)).Append('\n');
        }
        return sb.ToString();
    }

    public bool ApplyGumps(long serial, string uoPath, bool repair, List<string> conflicts)
    {
        var idx = ReadIndex(serial);
        if (idx is null) return false;
        var gumps = idx.Where(kv => kv.Key.StartsWith(GumpsSub + "/", StringComparison.Ordinal))
            .ToDictionary(kv => kv.Key[(GumpsSub.Length + 1)..], kv => kv.Value, StringComparer.OrdinalIgnoreCase);
        var ledger = GumpLedger.Load(Path.Combine(uoPath, "Gumps"));
        if (ledger.LoadWarning is not null) log.Warn("Gumps ledger: " + ledger.LoadWarning);
        var before = JsonSerializer.Serialize(ledger.Files);
        bool changed = false;
        foreach (var (name, sha) in gumps)
        {
            try
            {
                var a = ledger.Decide(name, sha);
                if (a == GumpAction.ConflictForeign || (a == GumpAction.ConflictModified && !repair))
                {
                    conflicts.Add($"Gumps\\{name}: {a}, left untouched");
                    log.Warn($"conflict: Gumps\\{name} {a}; not overwriting");
                    continue;
                }
                if (a is GumpAction.AlreadyPresent) continue;
                ledger.Install(name, PathOf(serial, GumpsSub + "/" + name), sha, a, repairModified: repair);
                changed = true;
                log.Info($"installed Gumps\\{name} ({a}) from version {serial}");
            }
            catch (Exception e) when (e is IOException or UnauthorizedAccessException)
            {
                conflicts.Add($"Gumps\\{name}: {e.Message}");
                log.Warn($"Gumps\\{name} not installed: {e.Message}");
            }
        }
        try
        {
            foreach (var r in ledger.Retire(gumps.Keys)) { changed = true; log.Info($"retired Gumps\\{r}"); }
        }
        catch (Exception e) when (e is IOException or UnauthorizedAccessException) { log.Warn("retire failed: " + e.Message); }
        if (changed || JsonSerializer.Serialize(ledger.Files) != before)
        {
            try { ledger.Save(); changed = true; }
            catch (Exception e) when (e is IOException or UnauthorizedAccessException) { log.Warn("ledger save failed: " + e.Message); }
        }
        return changed;
    }
}
